#!/usr/bin/env python3
"""Generates lib/GalenaRuntime/src/generated_programs.hpp from programs/*.resy.

Runs as a PlatformIO pre-build script (see `extra_scripts` in platformio.ini).
Each .resy file becomes a C++ raw-string literal so the source is embedded into
the firmware at build time, no filesystem involved.

Before every build the program to run is chosen interactively and the choice is
written into the single `const char* source = ...;` line of esp32/main.cpp. Only
that identifier changes; the .resy sources stay in their own files.

The generated files are only rewritten when their content actually changes, so an
unchanged programs/ folder does not trigger recompilation.

Pass --no-select to regenerate the header without touching main.cpp.
"""

import os
import re
import sys


def project_root():
    # PlatformIO execs this file through SCons, where __file__ is absent, so ask
    # the project environment first; fall back to plain-script execution.
    try:
        return Import("projenv")["PROJECT_DIR"]
    except Exception:
        pass
    if "__file__" in globals():
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.getcwd()


def programs_dir(root):
    return os.path.join(root, "programs")


def output_path(root):
    # A shared library, because both build targets include this header and
    # PlatformIO compiles the library for the firmware automatically.
    return os.path.join(
        root, "lib", "GalenaRuntime", "src", "generated_programs.hpp")


def main_cpp_path(root):
    return os.path.join(root, "esp32", "main.cpp")


# The one line in esp32/main.cpp that picks the program to run. Only the
# identifier between `=` and `;` is ever rewritten.
#
# An optional namespace qualifier is part of the prefix on purpose: main.cpp may
# spell the selection `resiris_programs::features_resy`, and rewriting the line
# has to preserve that qualifier instead of silently stripping it.
SELECTION_RE = re.compile(
    r"^(?P<prefix>[ \t]*const[ \t]+char[ \t]*\*[ \t]*source[ \t]*=[ \t]*)"
    r"(?:[A-Za-z_][A-Za-z0-9_]*[ \t]*::[ \t]*)*"
    r"(?P<identifier>[A-Za-z_][A-Za-z0-9_]*)"
    r"(?P<suffix>[ \t]*;[ \t]*)$",
    re.MULTILINE)


def sanitized_identifier(stem):
    identifier = re.sub(r"[^0-9A-Za-z_]", "_", stem)
    if not identifier:
        identifier = "program"
    if identifier[0].isdigit():
        identifier = "_" + identifier
    return identifier


def pick_delimiter(content):
    """A raw-string delimiter that cannot appear as a terminator in `content`.

    A C++ raw string `R"DELIM(...)DELIM"` ends at the first `)DELIM"` sequence,
    so choose DELIM such that `)` + DELIM + `"` does not occur in the file.
    """
    delimiter = "RESY"
    counter = 0
    while (")" + delimiter + '"') in content:
        counter += 1
        delimiter = "RESY_{}".format(counter)
    return delimiter


def load_programs(root):
    folder = programs_dir(root)
    if not os.path.isdir(folder):
        return []
    programs = []
    for filename in sorted(os.listdir(folder)):
        if not filename.endswith(".resy"):
            continue
        path = os.path.join(folder, filename)
        with open(path, "r", encoding="utf-8-sig") as handle:
            content = handle.read()
        stem = filename[:-len(".resy")]
        programs.append({
            "file": filename,
            "path": os.path.join("programs", filename).replace(os.sep, "/"),
            "name": stem,
            "identifier": sanitized_identifier(stem) + "_resy",
            "content": content,
        })
    return programs


def build_header(programs):
    lines = []
    lines.append("// Generated by scripts/generate_programs.py. DO NOT EDIT.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstring>")
    lines.append("")
    lines.append("namespace resiris_programs {")
    lines.append("")

    for program in programs:
        content = program["content"]
        if not content.endswith("\n"):
            content += "\n"
        delimiter = pick_delimiter(content)
        lines.append("// {}".format(program["path"]))
        lines.append("constexpr const char* {} =".format(program["identifier"]))
        # Emitted as a single line so the embedded source stays byte-identical
        # to the .resy file (content already ends with a newline).
        lines.append('R"{}('.format(delimiter) + content + '){}";'.format(delimiter))
        lines.append("")

    lines.append("struct ResyProgram {")
    lines.append("    const char* file;")
    lines.append("    const char* name;")
    lines.append("    const char* identifier;")
    lines.append("    const char* source;")
    lines.append("};")
    lines.append("")
    lines.append("constexpr ResyProgram kResyPrograms[] = {")
    if not programs:
        # A zero-sized array is not valid C++; keep the table well-formed so an
        # empty programs/ folder still builds.
        lines.append("    {nullptr, nullptr, nullptr, nullptr},")
    for program in programs:
        lines.append('    {{"{}", "{}", "{}", {}}},'.format(
            program["path"], program["name"], program["identifier"],
            program["identifier"]))
    lines.append("};")
    lines.append("")
    lines.append("constexpr int kResyProgramCount = {};".format(len(programs)))
    lines.append("")
    lines.append("// Returns the .resy file name owning `source`, or nullptr.")
    lines.append("inline const char* resy_program_name(const char* source) {")
    lines.append("    for (int i = 0; i < kResyProgramCount; ++i) {")
    lines.append("        if (kResyPrograms[i].source == source) {")
    lines.append("            return kResyPrograms[i].file;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("// Returns the entry whose identifier names a")
    lines.append("// `const char* source = <identifier>;` selection, or nullptr. This is how")
    lines.append("// a host build resolves which program the firmware build selected,")
    lines.append("// without depending on the identifier naming convention.")
    lines.append("inline const ResyProgram* resy_program_by_identifier(")
    lines.append("    const char* identifier) {")
    lines.append("    if (identifier == nullptr) {")
    lines.append("        return nullptr;")
    lines.append("    }")
    lines.append("    for (int i = 0; i < kResyProgramCount; ++i) {")
    lines.append("        const char* candidate = kResyPrograms[i].identifier;")
    lines.append("        if (candidate != nullptr &&")
    lines.append("            std::strcmp(candidate, identifier) == 0) {")
    lines.append("            return &kResyPrograms[i];")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace resiris_programs")
    lines.append("")
    return "\n".join(lines)


def write_header(destination, header):
    try:
        existing = open(destination, "r", encoding="utf-8").read()
    except OSError:
        existing = None

    if existing == header:
        print("generate_programs: {} up to date".format(destination))
        return

    with open(destination, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header)
    print("generate_programs: {} programs -> {}".format(
        header.count("constexpr const char* "), destination))


def select_program(programs):
    """Asks which .resy program this build should run. Always asks."""
    print("")
    print("Build Resiris program")
    print("")
    print("Available Resiris programs:")
    print("")
    for number, program in enumerate(programs, 1):
        print("  {}. {}".format(number, program["file"]))
    print("")

    last = len(programs)
    while True:
        try:
            answer = input("Select program to run (1-{}): ".format(last))
        except EOFError:
            print("")
            print("generate_programs: ERROR: no answer on stdin, but the "
                  "program must be selected for every build.")
            print("  Run the build from an interactive terminal.")
            sys.exit(1)

        answer = answer.strip()
        if answer.isdigit() and 1 <= int(answer) <= last:
            return programs[int(answer) - 1]

        if answer.isdigit():
            print("  '{}' is out of range, pick 1-{}.".format(answer, last))
        else:
            print("  '{}' is not a number, pick 1-{}.".format(answer, last))


def current_selection(root):
    """The identifier esp32/main.cpp currently selects, or None."""
    try:
        with open(main_cpp_path(root), "r", encoding="utf-8") as handle:
            content = handle.read()
    except OSError:
        return None
    match = SELECTION_RE.search(content)
    return match.group("identifier") if match else None


def keep_current_selection(root, programs):
    """Program matching main.cpp's current selection (used by --no-select)."""
    identifier = current_selection(root)
    for program in programs:
        if program["identifier"] == identifier:
            return program
    return programs[0]


def update_main_selection(root, program):
    """Rewrites only the identifier on the `const char* source = ...;` line."""
    path = main_cpp_path(root)
    try:
        with open(path, "r", encoding="utf-8") as handle:
            content = handle.read()
    except OSError as error:
        print("generate_programs: ERROR: cannot read {}: {}".format(path, error))
        sys.exit(1)

    matches = list(SELECTION_RE.finditer(content))
    if len(matches) != 1:
        print("generate_programs: ERROR: expected exactly one "
              "`const char* source = <program>;` line in {}, found {}.".format(
                  path, len(matches)))
        sys.exit(1)

    match = matches[0]
    identifier = program["identifier"]
    if match.group("identifier") == identifier:
        print("generate_programs: main.cpp already selects {} ({})".format(
            program["path"], identifier))
        return

    updated = content[:match.start("identifier")] + identifier + \
        content[match.end("identifier"):]
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(updated)
    print("generate_programs: main.cpp program -> {} ({})".format(
        program["path"], identifier))


def main():
    root = project_root()
    programs = load_programs(root)

    if not programs:
        print("generate_programs: ERROR: no .resy files in {}".format(
            programs_dir(root)))
        print("  Add at least one .resy program, then build again.")
        sys.exit(1)

    print("generate_programs: {} program(s) found in {}".format(
        len(programs), programs_dir(root)))

    if "--no-select" in sys.argv:
        program = keep_current_selection(root, programs)
        print("generate_programs: --no-select, keeping {}".format(program["path"]))
    else:
        program = select_program(programs)

    write_header(output_path(root), build_header(programs))
    update_main_selection(root, program)


# PlatformIO executes extra scripts by importing them, so main() must run at
# import time; it also stays usable as a standalone script.
main()