#!/usr/bin/env python3
"""Generates lib/GalenaRuntime/src/generated_modules.hpp from the module headers.

Every .hpp in lib/Resiris/modules/ is one native module, and this turns the
folder into the registry contents, so adding a module means adding two files and
nothing else. Nothing has to be registered by hand.

The generated header owns exactly one thing: make_modules(), which returns the
freshly constructed modules. galena_runtime.cpp hands that straight to
ModuleRegistry.

Two conventions make that possible, and the generator refuses to guess:

  1. The header must declare exactly one class deriving from Module. That class
     name is what the generated list instantiates, so there is no naming
     convention to follow and no second place to update.
  2. The class must be default-constructible. The generator can only ever write
     make_shared<Name>(), so a module that needs data from the host asks for it
     instead of taking a constructor argument: Module::on_registered() gives it
     the registry, and platform.hpp carries what the registry cannot.

Runs as a PlatformIO pre-build script (see extra_scripts in platformio.ini) and
as a plain script, so the desktop build can use it too. It never prompts: the
output only depends on the folder, so there is nothing to ask about. The header
is rewritten only when its content changes, so an unchanged folder does not
trigger recompilation.
"""

import os
import re
import sys


def project_root():
    # PlatformIO execs this file through SCons, where __file__ is absent, so ask
    # the project environment first; fall back to plain-script execution.
    try:
        return Import("projenv")["PROJECT_DIR"]
    except Exception:
        pass
    if "__file__" in globals():
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.getcwd()


def modules_dir(root):
    # A shared library, because both build targets include the generated header
    # and PlatformIO compiles Resiris for the firmware automatically.
    return os.path.join(root, "lib", "Resiris", "modules")


def output_path(root):
    return os.path.join(
        root, "lib", "GalenaRuntime", "src", "generated_modules.hpp")


def fail(message):
    print("generate_modules: ERROR: {}".format(message))
    sys.exit(1)


# `class RsMathModule : public Module`, plus the qualified spellings
# `class rsiris::RsMathModule final : public resiris::Module`.
#
# The qualifier is optional, but a class deriving from something other than Module
# would be a helper, not a module, so requiring the public Module base is what
# keeps helpers in the same folder from being registered by accident.
MODULE_CLASS_RE = re.compile(
    r"^\s*(?:class|struct)\s+(?:[A-Za-z_][A-Za-z0-9_]*::)*"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*"
    r"(?:final\b)?\s*:\s*"
    r"(?:public\s+)?"
    r"(?:[A-Za-z_][A-Za-z0-9_]*::)*Module\b",
    re.MULTILINE)


def load_modules(root):
    """Every module header, sorted, each with the class name to instantiate."""
    folder = modules_dir(root)
    if not os.path.isdir(folder):
        fail("no module folder at {}".format(folder))

    modules = []
    for filename in sorted(os.listdir(folder)):
        if not filename.endswith(".hpp"):
            continue
        path = os.path.join(folder, filename)

        with open(path, "r", encoding="utf-8-sig") as handle:
            content = handle.read()

        if "#pragma once" not in content:
            fail("{}: a module header needs `#pragma once`".format(path))

        classes = [match.group("name") for match in
                   MODULE_CLASS_RE.finditer(content)]
        unique = []
        for name in classes:
            if name not in unique:
                unique.append(name)
        if len(unique) != 1:
            fail("{}: expected exactly one class deriving from Module, "
                 "found {}{}".format(
                     path, len(unique),
                     "" if not unique else ": " + ", ".join(unique)))

        modules.append({
            "file": filename,
            "path": "modules/" + filename,
            "class": unique[0],
        })

    if not modules:
        fail("no module headers in {}".format(folder))

    names = [module["class"] for module in modules]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        fail("two headers declare the same module class: {}".format(
            ", ".join(duplicates)))

    return modules


def build_header(modules):
    lines = []
    lines.append("// Generated by scripts/generate_modules.py. DO NOT EDIT.")
    lines.append("// Source: lib/Resiris/modules/*.hpp")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <memory>")
    lines.append("#include <vector>")
    lines.append("")
    lines.append('#include "System/module.hpp"')
    lines.append("")
    for module in modules:
        lines.append('#include "{}"'.format(module["path"]))
    lines.append("")
    lines.append("namespace galena_generated {")
    lines.append("")
    lines.append("// Every module in modules/, default-constructed and ready to")
    lines.append("// register. Sorted by file name, so the order does not depend on what")
    lines.append("// the filesystem happened to return.")
    lines.append("inline std::vector<std::shared_ptr<resiris::Module>> make_modules() {")
    lines.append("    return std::vector<std::shared_ptr<resiris::Module>>{")
    for module in modules:
        lines.append("        // {}".format(module["path"]))
        lines.append("        std::make_shared<resiris::{}>(),".format(
            module["class"]))
    lines.append("    };")
    lines.append("}")
    lines.append("")
    lines.append("// The class each file contributed, for build messages and tests.")
    lines.append("constexpr const char* kModuleSources[] = {")
    for module in modules:
        lines.append('    "{}",'.format(module["path"]))
    lines.append("};")
    lines.append("")
    lines.append("constexpr int kModuleCount = {};".format(len(modules)))
    lines.append("")
    lines.append("} // namespace galena_generated")
    lines.append("")
    return "\n".join(lines)


def write_header(destination, header):
    try:
        existing = open(destination, "r", encoding="utf-8").read()
    except OSError:
        existing = None

    if existing == header:
        print("generate_modules: {} up to date".format(destination))
        return

    with open(destination, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header)
    print("generate_modules: {} module(s) -> {}".format(
        header.count("std::make_shared<"), destination))


def main():
    root = project_root()
    modules = load_modules(root)
    print("generate_modules: {} module(s) found in {}".format(
        len(modules), modules_dir(root)))
    write_header(output_path(root), build_header(modules))


# PlatformIO executes extra scripts by importing them, so main() must run at
# import time; it also stays usable as a standalone script.
main()