#!/usr/bin/env python3
"""Generates src/generated_programs.hpp from programs/*.resy.

Runs as a PlatformIO pre-build script (see `extra_scripts` in platformio.ini).
Each .resy file becomes a C++ raw-string literal so the source is embedded into
the firmware at build time, no filesystem involved.

The header is only rewritten when its content actually changes, so an
unchanged programs/ folder does not trigger recompilation.
"""

import os
import re


def project_root():
    # PlatformIO execs this file through SCons, where __file__ is absent, so ask
    # the project environment first; fall back to plain-script execution.
    try:
        return Import("projenv")["PROJECT_DIR"]
    except Exception:
        pass
    if "__file__" in globals():
        return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    return os.getcwd()


def programs_dir(root):
    return os.path.join(root, "programs")


def output_path(root):
    return os.path.join(root, "src", "generated_programs.hpp")


def sanitized_identifier(stem):
    identifier = re.sub(r"[^0-9A-Za-z_]", "_", stem)
    if not identifier:
        identifier = "program"
    if identifier[0].isdigit():
        identifier = "_" + identifier
    return identifier


def pick_delimiter(content):
    """A raw-string delimiter that cannot appear as a terminator in `content`.

    A C++ raw string `R"DELIM(...)DELIM"` ends at the first `)DELIM"` sequence,
    so choose DELIM such that `)` + DELIM + `"` does not occur in the file.
    """
    delimiter = "RESY"
    counter = 0
    while (")" + delimiter + '"') in content:
        counter += 1
        delimiter = "RESY_{}".format(counter)
    return delimiter


def load_programs(root):
    folder = programs_dir(root)
    if not os.path.isdir(folder):
        return []
    programs = []
    for filename in sorted(os.listdir(folder)):
        if not filename.endswith(".resy"):
            continue
        path = os.path.join(folder, filename)
        with open(path, "r", encoding="utf-8-sig") as handle:
            content = handle.read()
        stem = filename[:-len(".resy")]
        programs.append({
            "file": filename,
            "path": os.path.join("programs", filename).replace(os.sep, "/"),
            "name": stem,
            "identifier": sanitized_identifier(stem) + "_resy",
            "content": content,
        })
    return programs


def build_header(programs):
    lines = []
    lines.append("// Generated by scripts/generate_programs.py. DO NOT EDIT.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("namespace resiris_programs {")
    lines.append("")

    for program in programs:
        content = program["content"]
        if not content.endswith("\n"):
            content += "\n"
        delimiter = pick_delimiter(content)
        lines.append("// {}".format(program["path"]))
        lines.append("constexpr const char* {} =".format(program["identifier"]))
        # Emitted as a single line so the embedded source stays byte-identical
        # to the .resy file (content already ends with a newline).
        lines.append('R"{}('.format(delimiter) + content + '){}";'.format(delimiter))
        lines.append("")

    lines.append("struct ResyProgram {")
    lines.append("    const char* file;")
    lines.append("    const char* name;")
    lines.append("    const char* source;")
    lines.append("};")
    lines.append("")
    lines.append("constexpr ResyProgram kResyPrograms[] = {")
    if not programs:
        # A zero-sized array is not valid C++; keep the table well-formed so an
        # empty programs/ folder still builds.
        lines.append("    {nullptr, nullptr, nullptr},")
    for program in programs:
        lines.append('    {{"{}", "{}", {}}},'.format(
            program["path"], program["name"], program["identifier"]))
    lines.append("};")
    lines.append("")
    lines.append("constexpr int kResyProgramCount = {};".format(len(programs)))
    lines.append("")
    lines.append("// Returns the .resy file name owning `source`, or nullptr.")
    lines.append("inline const char* resy_program_name(const char* source) {")
    lines.append("    for (int i = 0; i < kResyProgramCount; ++i) {")
    lines.append("        if (kResyPrograms[i].source == source) {")
    lines.append("            return kResyPrograms[i].file;")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace resiris_programs")
    lines.append("")
    return "\n".join(lines)


def main():
    root = project_root()
    programs = load_programs(root)
    header = build_header(programs)
    destination = output_path(root)

    try:
        existing = open(destination, "r", encoding="utf-8").read()
    except OSError:
        existing = None

    if existing == header:
        print("generate_programs: {} up to date ({} programs)".format(
            destination, len(programs)))
        return

    with open(destination, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header)
    print("generate_programs: {} programs -> {}".format(
        len(programs), destination))


# PlatformIO executes extra scripts by importing them, so main() must run at
# import time; it also stays usable as a standalone script.
main()