// Generated by scripts/generate_modules.py. DO NOT EDIT.
// Source: lib/Resiris/modules/*.hpp
#pragma once

#include <memory>
#include <vector>

#include "System/module.hpp"

#include "modules/rsbase.hpp"
#include "modules/rsmath.hpp"
#include "modules/rssystem.hpp"

namespace galena_generated {

// Every module in modules/, default-constructed and ready to
// register. Sorted by file name, so the order does not depend on what
// the filesystem happened to return.
inline std::vector<std::shared_ptr<resiris::Module>> make_modules() {
    return std::vector<std::shared_ptr<resiris::Module>>{
        // modules/rsbase.hpp
        std::make_shared<resiris::RsBaseModule>(),
        // modules/rsmath.hpp
        std::make_shared<resiris::RsMathModule>(),
        // modules/rssystem.hpp
        std::make_shared<resiris::RsSystemModule>(),
    };
}

// The class each file contributed, for build messages and tests.
constexpr const char* kModuleSources[] = {
    "modules/rsbase.hpp",
    "modules/rsmath.hpp",
    "modules/rssystem.hpp",
};

constexpr int kModuleCount = 3;

} // namespace galena_generated
