// Generated by scripts/generate_programs.py. DO NOT EDIT.
#pragma once

#include <cstring>

namespace resiris_programs {

// programs/features.resy
constexpr const char* features_resy =
R"RESY(<include> RSMath, RSBase

c FPS float = 10.0
c LIMIT int = 10

v a int = 10
v b int = 3
v x float = 2.5
v y float = 4.0
v s string = "Hello"
v t string = "World"
v flag bool = true
v u UnknownObject = 42
v index int = 0

print_cmd(a)
print_cmd(b)
print_cmd(a + b)
print_cmd(a - b)
print_cmd(a * b)
print_cmd(a % b)
print_cmd(7 % 3)
print_cmd(-7 % 3)
print_cmd(7 % -3)
print_cmd(x + y)
print_cmd(x * y)
print_cmd(y / x)
print_cmd(0.1 + 0.2)
print_cmd(-x)
print_cmd(100.0)
print_cmd(0.00001)
print_cmd(1000000.0)
print_cmd(x * 1000000.0)
print_cmd(s + " " + t)
print_cmd(a == 10)
print_cmd(a != b)
print_cmd(b < a)
print_cmd(s < t)
print_cmd(flag)
print_cmd(flag == (a > b))
print_cmd(u.type())
print_cmd(x.type())
print_cmd(s.type())
print_cmd(flag.type())
print_cmd(x.type(int))
print_cmd(b.type(float))
print_cmd(b.type(string))
print_cmd(u.type(bool))
print_cmd(b.type(bool))
print_cmd(s.string())
print_cmd(str(a))
print_cmd(LIMIT)

v dec float = 26.0
dec += 5
print_cmd(dec)
dec -= 2
print_cmd(dec)
dec *= 2
print_cmd(dec)
dec /= 2.0
print_cmd(dec)

fn classify(val):
	if val.type() == "int":
		return "int value"
	elif val.type() == "float":
		return "float value"
	elif val.type() == "bool":
		return "bool value"
	else:
		return "string value"

fn describe(n):
	mat n:
		1:
			return "one"
		2:
			return "two"
		3:
			return "three"
		else:
			return "many"

print_cmd(classify(a))
print_cmd(classify(x))
print_cmd(classify(flag))
print_cmd(classify(s))
print_cmd(describe(1))
print_cmd(describe(2))
print_cmd(describe(7))

mat x.type():
	int:
		print_cmd("mat says int")
	float:
		print_cmd("mat says float")
	else:
		print_cmd("mat says other")

v counter FunctionalObject = FunctionalObject.new():
	index += 1
	return index
print_cmd(counter())
print_cmd(counter())
print_cmd(counter())

print_cmd(RSMath.abs(-7))
print_cmd(RSMath.abs(-7.5))
print_cmd(RSMath.sqrt(16.0))
print_cmd(RSMath.cbrt(27.0))
print_cmd(RSMath.pow(2.0, 10.0))
print_cmd(RSMath.floor(3.7))
print_cmd(RSMath.ceil(3.2))
print_cmd(RSMath.round(3.5))
print_cmd(RSMath.round(2.5))
print_cmd(RSMath.ln(RSMath[E]))
print_cmd(RSMath.log10(1000.0))
print_cmd(RSMath.sin(0.0))
print_cmd(RSMath.cos(0.0))
print_cmd(RSMath.tan(0.0))
print_cmd(RSMath.atan(1.0))
print_cmd(RSMath.hypot(3.0, 4.0))
print_cmd(RSMath.pythagoras(3.0, 4.0))
print_cmd(RSMath.factorial(10))
print_cmd(RSMath.ncr(5, 2))
print_cmd(RSMath.npr(5, 2))
print_cmd(RSMath.gcd(12, 18))
print_cmd(RSMath.lcm(4, 6))
print_cmd(RSMath.mod(7, 3))
print_cmd(RSMath.mod(-7, 3))
print_cmd(RSMath.min(2, 7))
print_cmd(RSMath.max(2, 7))
print_cmd(RSMath.clamp(5.5, 1.0, 3.0))
print_cmd(RSMath.is_nan(1.0))
print_cmd(RSMath.is_inf(1.0))
print_cmd(RSMath.is_finite(1.0))
print_cmd(RSMath[PI])
print_cmd(RSMath[E])

v timer ModuleObject = RSBase.await()
timer.set_timer(0.35)
timer.on_timeout("timer_callback")
START():
	print_cmd("start lifecycle")
PROCESS(FPS):
	print_cmd(timer.process())
fn timer_callback():
	print_cmd("timer callback fired")
)RESY";

// programs/recursion_depth.resy
constexpr const char* recursion_depth_resy =
R"RESY(fn descend(n):
	if n <= 0:
		return 0
	print_cmd(n)
	return descend(n - 1)

fn probe(depth):
	print_cmd(depth)
	return descend(depth)

probe(1)
probe(2)
probe(3)
probe(4)
probe(5)
print_cmd("done")
)RESY";

// programs/rssystem.resy
constexpr const char* rssystem_resy =
R"RESY(<include> RSSystem

## RSSystem in the portable subset: the facts that have an answer on both
## targets, so this program runs the same on a PC and on the device.
##
## The hardware facts -- chip_model, chip_revision, cpu_speed, memory_total,
## memory_free, memory_used, memory_min_free, psram_size, flash_total and
## flash_used -- read the ESP32's own silicon and flash. On a PC they raise a
## ModuleError naming the function rather than answering with a number that
## describes some other machine, so this program does not call them: on a host it
## would stop here. report() collects them anyway, which is what makes it the
## call worth reaching for on a device.

c FPS float = 4.0

v frame int = 0

START():
	print_cmd("modules: " + RSSystem.modules())
	print_cmd("cores:   " + str(RSSystem.cpu_cores()))
	print_cmd("uptime:  " + str(RSSystem.uptime()))
	print_cmd("load:    " + str(RSSystem.cpu_load()))

)RESY";

// programs/test.resy
constexpr const char* test_resy =
R"RESY(v x int = 10
v y int = 20
v result int = x + y
print_cmd(result)
)RESY";

struct ResyProgram {
    const char* file;
    const char* name;
    const char* identifier;
    const char* source;
};

constexpr ResyProgram kResyPrograms[] = {
    {"programs/features.resy", "features", "features_resy", features_resy},
    {"programs/recursion_depth.resy", "recursion_depth", "recursion_depth_resy", recursion_depth_resy},
    {"programs/rssystem.resy", "rssystem", "rssystem_resy", rssystem_resy},
    {"programs/test.resy", "test", "test_resy", test_resy},
};

constexpr int kResyProgramCount = 4;

// Returns the .resy file name owning `source`, or nullptr.
inline const char* resy_program_name(const char* source) {
    for (int i = 0; i < kResyProgramCount; ++i) {
        if (kResyPrograms[i].source == source) {
            return kResyPrograms[i].file;
        }
    }
    return nullptr;
}

// Returns the entry whose identifier names a
// `const char* source = <identifier>;` selection, or nullptr. This is how
// a host build resolves which program the firmware build selected,
// without depending on the identifier naming convention.
inline const ResyProgram* resy_program_by_identifier(
    const char* identifier) {
    if (identifier == nullptr) {
        return nullptr;
    }
    for (int i = 0; i < kResyProgramCount; ++i) {
        const char* candidate = kResyPrograms[i].identifier;
        if (candidate != nullptr &&
            std::strcmp(candidate, identifier) == 0) {
            return &kResyPrograms[i];
        }
    }
    return nullptr;
}

} // namespace resiris_programs
